export const posts = [
    {
        id: 1,
        title: 'Equipment Versus Photographer – Which Matters More?',
        category: 'Style',
        image: 'images/lifestyle-image-1.jpeg',
        size: 'large',
        block: 'lifestyle',
    },
    {
        id: 2,
        title: 'Tips for Creating Awesome Double Exposures In-Camera',
        category: 'Travel',
        image: 'images/lifestyle-image-2.jpeg',
        size: 'medium',
        block: 'lifestyle',
    },
    {
        id: 3,
        title: '5 Top Tips for Marketing Your Photography Business Successfully',
        category: 'Interior',
        image: 'images/lifestyle-image-3.jpeg',
        size: 'medium',
        block: 'lifestyle',
    },
    {
        id: 4,
        title: 'An Introduction to Amazing Abstract Automotive Photography',
        category: 'Lifestyle',
        image: 'images/lifestyle-image-4.jpeg',
        size: 'medium',
        block: 'lifestyle',
    },
    {
        id: 5,
        title: '5 Essential Tools for Wedding Photography That Aren’t Gear-Related',
        category: 'Style',
        image: 'images/lifestyle-image-5.jpeg',
        size: 'medium',
        block: 'lifestyle',
    },
    {
        id: 6,
        title: 'How to Be a Second Shooter at Weddings and Why It’s Important',
        category: 'Lifestyle',
        image: 'images/city-life-image-1.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'cityLife',
    },
    {
        id: 7,
        title: 'How to Photograph Food Coloring or Dye Dropped in Water',
        category: 'Style',
        image: 'images/city-life-image-2.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'cityLife',
    },
    {
        id: 8,
        title: 'How to Add a Texture to Your Photos – a Tutorial on Adding Textures',
        category: 'Travel',
        image: 'images/city-life-image-3.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'cityLife',
    },
    {
        id: 9,
        title: '9 Ways to Use Reflections More Creatively for Stunning Photography',
        category: 'Lifestyle',
        image: 'images/city-life-image-4.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'cityLife',
    },
    {
        id: 10,
        title: 'Your Ultimate Guide to Hanging Wall Art and Photos Like a Pro',
        category: 'Style',
        image: 'images/city-life-image-5.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'cityLife',
    },
    {
        id: 11,
        title: 'The 9 Most Powerful Composition Rules for Dynamic Landscape Shots',
        category: 'Lifestyle',
        image: 'images/street-views-image-1.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'streetViews',
    },
    {
        id: 12,
        title: 'How to Create a Panoramic Photograph With a Tilt-Shift Lens',
        category: 'Lifestyle',
        image: 'images/street-views-image-2.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'streetViews',
    },
    {
        id: 13,
        title: 'Underexposure vs Overexposure – a Beginner’s Guide',
        category: 'Interior',
        image: 'images/street-views-image-3.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'large',
        block: 'streetViews',
    },
    {
        id: 14,
        title: 'How to Photograph Interior Domes of Popular Landmarks',
        category: 'Style',
        image: 'images/street-views-image-4.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'streetViews',
    },
    {
        id: 15,
        title: 'The Importance of Straightening the Horizon and Aligning Lines',
        category: 'Interior',
        image: 'images/street-views-image-5.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'streetViews',
    },
    {
        id: 16,
        title: '11 Travel Photography Tips When Traveling With Young Children',
        category: 'Travel',
        image: 'images/most-recent-image-1.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'mostRecent',
    },
    {
        id: 17,
        title: 'Equipment Versus Photographer – Which Matters More?',
        category: 'Style',
        image: 'images/most-recent-image-2.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'mostRecent',
    },
    {
        id: 18,
        title: 'Capture Flower Photography Outside: Diffuse Light With a DIY Studio',
        category: 'Style',
        image: 'images/most-recent-image-3.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'mostRecent',
    },
    {
        id: 19,
        title: '6 Scenarios to Try for More Interesting Beach Photography',
        category: 'Lifetyle',
        image: 'images/most-recent-image-4.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'mostRecent',
    },
    {
        id: 20,
        title: 'How to Add a Texture to Your Photos – a Tutorial on Adding Textures',
        category: 'Travel',
        image: 'images/most-recent-image-5.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'mostRecent',
    },
    {
        id: 21,
        title: '5 Essential Tools for Wedding Photography That Aren’t Gear-Related',
        category: 'Style',
        image: 'images/most-recent-image-6.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'mostRecent',
    },
    {
        id: 22,
        title: 'Recommended Filters to Use With Black and White Photography',
        category: 'Travel',
        image: 'images/most-recent-image-7.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'mostRecent',
    },
    {
        id: 23,
        title: '7 Things All Photographers Need to Know About Copyright',
        category: 'Style',
        image: 'images/most-recent-image-8.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'mostRecent',
    },
    {
        id: 24,
        title: 'How to Be a Second Shooter at Weddings and Why It’s Important',
        category: 'Lifestyle',
        image: 'images/most-recent-image-9.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'mostRecent',
    },
    {
        id: 25,
        title: 'Everything You Need to Know About Macro Photography',
        category: 'Travel',
        image: 'images/most-recent-image-10.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'mostRecent',
    },
    {
        id: 26,
        title: 'How to Photograph Fireworks – Everything You Need to Know',
        category: 'Lifestyle',
        image: 'images/most-recent-image-11.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'mostRecent',
    },
    {
        id: 27,
        title: 'Do Cheap Photographers Take Work Away From the Rest of Us?',
        category: 'Travel',
        image: 'images/most-recent-image-12.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'mostRecent',
    },
    {
        id: 28,
        title: 'How Using Props in Portraits Can Make Your Photos More Interesting',
        category: 'Lifestyle',
        image: 'images/blog-image-1.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        description: 'Structured gripped tape invisible moulded cups for suppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button...',
        block: 'blog',
    },
    {
        id: 29,
        title: 'How to Protect Your Camera Against Lens Fungal Damage',
        category: 'Interior',
        image: 'images/blog-image-2.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        description: 'Structured gripped tape invisible moulded cups for suppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button...',
        block: 'blog',
    },
    {
        id: 30,
        title: 'Do Cheap Photographers Take Work Away From the Rest of Us?',
        category: 'Travel',
        image: 'images/blog-image-3.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        description: 'Structured gripped tape invisible moulded cups for suppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button...',
        block: 'blog',
    },
    {
        id: 31,
        title: '9 Ways to Use Reflections More Creatively for Stunning Photography',
        category: 'Lifestyle',
        image: 'images/blog-image-4.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        description: 'Structured gripped tape invisible moulded cups for suppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button...',
        block: 'blog',
    },
    {
        id: 32,
        title: 'Equipment Versus Photographer – Which Matters More?',
        category: 'Style',
        image: 'images/blog-image-5.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        description: 'Structured gripped tape invisible moulded cups for suppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button...',
        block: 'blog',
    },
    {
        id: 33,
        title: 'Tips for Creating Awesome Double Exposures In-Camera',
        category: 'Travel',
        image: 'images/blog-image-6.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        description: 'Structured gripped tape invisible moulded cups for suppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button...',
        block: 'blog',
    },
]
