export const posts = [
    {
        id: 1,
        title: 'Equipment Versus Photographer – Which Matters More?',
        category: 'Style',
        image: 'images/lifestyle-image-1.jpeg',
        size: 'large',
        block: 'lifestyle',
    },
    {
        id: 2,
        title: 'Tips for Creating Awesome Double Exposures In-Camera',
        category: 'Travel',
        image: 'images/lifestyle-image-2.jpeg',
        size: 'medium',
        block: 'lifestyle',
    },
    {
        id: 3,
        title: '5 Top Tips for Marketing Your Photography Business Successfully',
        category: 'Interior',
        image: 'images/lifestyle-image-3.jpeg',
        size: 'medium',
        block: 'lifestyle',
    },
    {
        id: 4,
        title: 'An Introduction to Amazing Abstract Automotive Photography',
        category: 'Lifestyle',
        image: 'images/lifestyle-image-4.jpeg',
        size: 'medium',
        block: 'lifestyle',
    },
    {
        id: 5,
        title: '5 Essential Tools for Wedding Photography That Aren’t Gear-Related',
        category: 'Style',
        image: 'images/lifestyle-image-5.jpeg',
        size: 'medium',
        block: 'lifestyle',
    },
    {
        id: 6,
        title: 'How to Be a Second Shooter at Weddings and Why It’s Important',
        category: 'Lifestyle',
        image: 'images/city-life-image-1.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'cityLife',
    },
    {
        id: 7,
        title: 'How to Photograph Food Coloring or Dye Dropped in Water',
        category: 'Style',
        image: 'images/city-life-image-2.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'cityLife',
    },
    {
        id: 8,
        title: 'How to Add a Texture to Your Photos – a Tutorial on Adding Textures',
        category: 'Travel',
        image: 'images/city-life-image-3.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'cityLife',
    },
    {
        id: 9,
        title: '9 Ways to Use Reflections More Creatively for Stunning Photography',
        category: 'Lifestyle',
        image: 'images/city-life-image-4.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'cityLife',
    },
    {
        id: 10,
        title: 'Your Ultimate Guide to Hanging Wall Art and Photos Like a Pro',
        category: 'Style',
        image: 'images/city-life-image-5.jpeg',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        size: 'medium',
        block: 'cityLife',
    },
]
